name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: test.tex
      - name: Commit and Push new file         
        run: |           
            git config user.name "bot"           
            git add .           
            git commit -m "add PDF file"           
            git push
